// ─────────────────────────────────────────────
//  COMMON PORTFOLIO DATABASE  (vanilla JS)
// ─────────────────────────────────────────────

window.portfolioData = {

  profile: {
    name:     'Kushagra Katiyar',
    title:    'CS @ University of Florida | Full-Stack Developer',
    location: 'Lake Mary, Florida',
    bio:      "I am pursuing a bachelor's in Computer Science at the University of Florida. I specialize in Agentic AI Systems, Full Stack Development, and UI/UX Design. I have shipped real-world applications and hold leadership on campus, demonstrating skills in teamwork, communication, and problem-solving. Outside of tech, my interests include gaming, cars, and Taekwondo. I post flute videos on TikTok and Instagram, accumulating over 500,000 views.",
    avatar:   'assets/profile_picture_landing.jpg',
    resume:   'assets/Kushagra_Katiyar_Software_Engineering_Resume.pdf',
  },

  social: [
    { href: 'https://github.com/KushagraKatiyar06',         icon: 'assets/github_icon.svg',    label: 'GitHub' },
    { href: 'https://www.linkedin.com/in/kushagrakatiyar/', icon: 'assets/linkedin_icon.svg',  label: 'LinkedIn' },
    { href: 'https://www.instagram.com/just_kushagra/',     icon: 'assets/instagram_icon.svg', label: 'Instagram' },
    { href: 'https://www.tiktok.com/@just_kushagra',        icon: 'assets/tiktok_icon.svg',    label: 'TikTok' },
  ],

  skills: {
    Languages: [
      { label: 'Python',     icon: 'assets/python.svg' },
      { label: 'C++',        icon: 'assets/cpp.svg' },
      { label: 'JavaScript', icon: 'assets/javascript.svg' },
      { label: 'TypeScript', icon: 'assets/typescript.svg' },
      { label: 'HTML',       icon: 'assets/html.svg' },
      { label: 'CSS',        icon: 'assets/css.svg' },
    ],
    Frameworks: [
      { label: 'React',      icon: 'assets/react.svg' },
      { label: 'Next.js',    icon: 'assets/nextjs.svg' },
      { label: 'Node.js',    icon: 'assets/nodejs.svg' },
      { label: 'Flask',      icon: 'assets/flask.svg' },
      { label: 'Vite',       icon: 'assets/vite.svg' },
      { label: 'Expo',       icon: 'assets/expo.svg' },
      { label: 'PostgreSQL', icon: 'assets/postgres.svg' },
    ],
    DevOps: [
      { label: 'Docker',     icon: 'assets/docker.svg' },
      { label: 'AWS',        icon: 'assets/aws.svg' },
      { label: 'GCP',        icon: 'assets/gcp.svg' },
      { label: 'Cloudflare', icon: 'assets/cloudflare.svg' },
    ],
    'AI / ML': [
      { label: 'OpenAI',     icon: 'assets/openai.svg' },
      { label: 'Gemini',     icon: 'assets/gemini.svg' },
      { label: 'TensorFlow', icon: 'assets/tensorflow.svg' },
      { label: 'MediaPipe',  icon: 'assets/mediapipe.svg' },
      { label: 'OpenCV',     icon: 'assets/opencv.svg' },
    ],
    Design: [
      { label: 'Figma',    icon: 'assets/figma.svg' },
      { label: 'Framer',   icon: 'assets/framer.svg' },
      { label: 'ShadCN',   icon: 'assets/shadcn.svg' },
      { label: 'AdobeXD',  icon: 'assets/adobexd.svg' },
    ],
  },

  experiences: [
    {
      type: 'leadership',
      org: 'GatorAI',
      role: 'Social Media Officer',
      duration: 'July 2025 \u2013 April 2026',
      location: 'Gainesville, Florida',
      logo: 'assets/orgs/gatorai.png',
      bullets: [
        'Boosted Instagram engagement by 2x, driving 150,000+ impressions in a single month through targeted content strategy.',
        'Represented GatorAI at tabling events, engaging 25+ students per session, bringing in 200+ attendees to GBMs.',
        'Arranged and designed scenes/graphics on OBS for weekly AI/ML lecture streams accumulating 900+ views per semester.',
      ],
      stack: [
        { label: 'Canva', icon: 'assets/canva.svg' },
        { label: 'OBS',   icon: 'assets/obs.svg' },
      ],
    },
    {
      type: 'extracurricular',
      org: 'Swamp Records',
      role: 'Software Engineer',
      duration: 'January 2026 \u2013 April 2026',
      location: 'Gainesville, Florida',
      logo: 'assets/orgs/swamprecords.jpg',
      bullets: [
        "Spearheaded the UI/UX design and frontend for Gainesville artist Alex Willow's digital presence, converting EPK into a website.",
        'Orchestrating a design-to-development pipeline by translating complex Figma prototypes into Next.js and React components.',
        'Collaborating with artist management to strategize a centralized design system and implemented TypeScript components.',
      ],
      stack: [
        { label: 'Next.js',    icon: 'assets/nextjs.svg' },
        { label: 'React',      icon: 'assets/react.svg' },
        { label: 'TypeScript', icon: 'assets/typescript.svg' },
        { label: 'Figma',      icon: 'assets/figma.svg' },
      ],
    },
    {
      type: 'extracurricular',
      org: 'Gator User Design',
      role: 'UI/UX Designer',
      duration: 'October 2025 \u2013 January 2026',
      location: 'Gainesville, Florida',
      logo: 'assets/orgs/gud.jfif',
      bullets: [
        'Executed user research for the UF CSFG Lab website, identifying critical friction points through qualitative stakeholder analysis.',
        'Architected design system and high-fidelity interactive prototypes in Figma, ensuring visual consistency across all lab pages.',
        'Redesigned the end-to-end user experience, creating user personas, iterating on wireframes based on direct feedback with Professor.',
      ],
      stack: [
        { label: 'Figma', icon: 'assets/figma.svg' },
      ],
    },
    {
      type: 'extracurricular',
      org: 'UF GatorAI',
      role: 'Software Team Lead',
      duration: 'September 2025 \u2013 January 2026',
      location: 'Gainesville, Florida',
      logo: 'assets/orgs/gatorai.png',
      bullets: [
        'Led end-to-end development of an Agentic AI video generation platform, achieving 20x cost reduction at $0.05 per minute.',
        'Full-stack using Next.js, Express.js and PostgreSQL, CloudFlare R2 deployed via Docker with continuous delivery.',
        'Orchestrated pipeline using Nebius, Flux Schnell, AWS Polly, and FFmpeg via REST APIs with Celery and Redis.',
      ],
      stack: [
        { label: 'Python',     icon: 'assets/python.svg' },
        { label: 'Next.js',    icon: 'assets/nextjs.svg' },
        { label: 'PostgreSQL', icon: 'assets/postgres.svg' },
        { label: 'Docker',     icon: 'assets/docker.svg' },
        { label: 'AWS',        icon: 'assets/aws.svg' },
        { label: 'Cloudflare', icon: 'assets/cloudflare.svg' },
        { label: 'FFmpeg',     icon: 'assets/ffmpeg.svg' },
      ],
    },
    {
      type: 'experience',
      org: 'Virtual Learning Lab',
      role: 'Undergraduate Research Assistant',
      duration: 'January 2026 \u2013 Present',
      location: 'University of Florida',
      logo: 'assets/orgs/college_of_education.jpg',
      bullets: [
        'Implementing LLM-as-a-judge to grade decodable texts used across 5+ elementary schools, improving child engagement.',
        'Developed RAG system to vectorize and store 200+ stories, resulting in prompt sizes reduced from 25,000 to 1000 tokens.',
        'Enforced data integrity across Llama, GPT and Gemini model outputs using Pydantic validation further cutting prompt costs.',
      ],
      stack: [
        { label: 'Python', icon: 'assets/python.svg' },
        { label: 'OpenAI', icon: 'assets/openai.svg' },
        { label: 'Gemini', icon: 'assets/gemini.svg' },
      ],
    },
    {
      type: 'leadership',
      org: 'UF GatorAI',
      role: 'Webmaster',
      duration: 'January 2026 \u2013 Present',
      location: 'Gainesville, Florida',
      logo: 'assets/orgs/gatorai.png',
      bullets: [
        "Full-stack development of GatorAI's web platform serving 500+ members with Next.js 14 and Supabase PostgreSQL.",
        'Engineered real-time semantic search with multi-field functionality across officer integrations.',
        'Managing platform ecosystem across 12+ officer roles and critical integrations.',
      ],
      stack: [
        { label: 'Next.js',    icon: 'assets/nextjs.svg' },
        { label: 'PostgreSQL', icon: 'assets/postgres.svg' },
        { label: 'TypeScript', icon: 'assets/typescript.svg' },
        { label: 'JavaScript', icon: 'assets/javascript.svg' },
      ],
    },
    {
      type: 'extracurricular',
      org: 'Dream Team Engineering',
      role: 'Software Engineer',
      duration: 'January 2026 \u2013 Present',
      location: 'Gainesville, Florida',
      logo: 'assets/orgs/dreamteam.png',
      bullets: [
        'Building a Kotlin Android app for Train-of-Four anesthesia testing, providing an alternative to $2000 of medical equipment.',
        'Engineered motion pipeline with MediaPipe ROI, optical flow stabilization, Savitzky-Golay filtering, and T4/T1 area ratio.',
        'Achieved 90% accuracy across 400+ Unity simulations and preparing for IRB-approved field trials at UF Shands Hospital.',
      ],
      stack: [
        { label: 'Java',      icon: 'assets/java.svg' },
        { label: 'OpenCV',    icon: 'assets/opencv.svg' },
        { label: 'MediaPipe', icon: 'assets/mediapipe.svg' },
        { label: 'Kotlin',    icon: 'assets/kotlin.svg' },
      ],
    },
    {
      type: 'leadership',
      org: 'TikTok',
      role: 'Content Creator',
      duration: 'December 2025 \u2013 Present',
      location: 'Lake Mary, Florida',
      logo: 'assets/orgs/tiktok.png',
      bullets: [
        'Posts flute videos accumulating 500,000+ cumulative views.',
        'Grown to 800+ followers.',
      ],
      stack: [],
    },
    {
      type: 'leadership',
      org: 'Computing Student Union',
      role: 'UI/UX Design Team Lead',
      duration: 'August 2025 \u2013 Present',
      location: 'Gainesville, Florida',
      logo: 'assets/orgs/csu.png',
      bullets: [
        'Managed UI/UX strategy for a campus-wide portal, streamlining event tracking for 200 CS students and 25 organizations.',
        'Leading the development of centralized design system including colors, typography and components.',
        'Developed high-fidelity prototypes in Figma emphasizing ADA accessibility requirements, resulting in 100 new active users.',
      ],
      stack: [
        { label: 'Figma',  icon: 'assets/figma.svg' },
        { label: 'ShadCN', icon: 'assets/shadcn.svg' },
      ],
    },
    {
      type: 'leadership',
      org: 'Computing Student Union',
      role: 'Membership Director',
      duration: 'May 2025 \u2013 January 2026',
      location: 'Gainesville, Florida',
      logo: 'assets/orgs/csu.png',
      bullets: [
        'Organized social events for 20+ UFCSU tech team members.',
        'Led recruitment workflows using Google Forms.',
        'Tracked metrics in Notion and Google Sheets.',
      ],
      stack: [
        { label: 'Notion',        icon: 'assets/notion.svg' },
        { label: 'Google Sheets', icon: 'assets/googlesheets.svg' },
      ],
    },
    {
      type: 'extracurricular',
      org: 'Computing Student Union',
      role: 'UI/UX Designer',
      duration: 'January 2025 \u2013 Present',
      location: 'Gainesville, Florida',
      logo: 'assets/orgs/csu.png',
      bullets: [
        'Designed UI/UX for 3+ products serving 100+ CS students and 25+ computing clubs.',
        'Integrated ShadCN components for modern industry standards.',
        'Developed and iterated 3-5 Figma prototypes per product.',
      ],
      stack: [
        { label: 'Figma',  icon: 'assets/figma.svg' },
        { label: 'ShadCN', icon: 'assets/shadcn.svg' },
      ],
    },
    {
      type: 'experience',
      org: 'English2Success',
      role: 'Software Engineering Intern',
      duration: 'February 2025 \u2013 July 2025',
      location: 'Remote',
      logo: 'assets/orgs/english2success.png',
      bullets: [
        'Designed a full-stack dashboard using Flask and Python, resulting in growth from 200 to 450+ global members.',
        'Migrated to PostgreSQL and integrated GPT-4o for automated tutor progress reporting, cutting 8 hours of weekly overhead.',
        'Used Gmail API and Google Service Accounts with Google Cloud to schedule 50+ weekly reminders and deploy dashboard.',
      ],
      stack: [
        { label: 'Python',     icon: 'assets/python.svg' },
        { label: 'Flask',      icon: 'assets/flask.svg' },
        { label: 'PostgreSQL', icon: 'assets/postgres.svg' },
        { label: 'Docker',     icon: 'assets/docker.svg' },
        { label: 'GCP',        icon: 'assets/gcp.svg' },
        { label: 'OpenAI',     icon: 'assets/openai.svg' },
      ],
    },
    {
      type: 'experience',
      org: 'Kickstand Technologies',
      role: 'Software Engineering Intern',
      duration: 'May 2023 \u2013 August 2023',
      location: 'Winter Springs, Florida',
      logo: 'assets/kickstand.png',
      bullets: [
        'Integrated Launch Library 2 in TypeScript to track and display rocket launches into mobile app with 50,000 downloads.',
        'Built Angular and Ionic UI components including countdown displays and agency filters, optimized for iOS and Android.',
        'Produced rocket launch highlight videos and branded intro sequences using DaVinci Resolve, reaching 5,000+ monthly views.',
      ],
      stack: [
        { label: 'TypeScript', icon: 'assets/typescript.svg' },
        { label: 'JavaScript', icon: 'assets/javascript.svg' },
        { label: 'HTML',       icon: 'assets/html.svg' },
        { label: 'CSS',        icon: 'assets/css.svg' },
      ],
    },
  ],

  projects: {
    live: [
      {
        name: 'Riva',
        subtitle: 'Agentic AI Browser & GTM Tool',
        image: 'assets/projects/riva.png',
        live: 'https://riva-frontend.pages.dev/',
        github: 'https://github.com/KushagraKatiyar06/Riva',
        video: 'https://youtu.be/WZFLMwTHqyA',
        figma: 'https://www.figma.com/design/k1YBhnEym2hMqIpKttI21B/Riva',
        users: '~5',
        stack: [
          { label: 'Next.js 15', icon: 'assets/nextjs.svg' },
          { label: 'React 19',   icon: 'assets/react.svg' },
          { label: 'TypeScript', icon: 'assets/typescript.svg' },
          { label: 'Python',     icon: 'assets/python.svg' },
          { label: 'Cloudflare', icon: 'assets/cloudflare.svg' },
          { label: 'Gemini',     icon: 'assets/gemini.svg' },
          { label: 'Figma',      icon: 'assets/figma.svg' },
        ],
      },
      {
        name: 'KeyFrame',
        subtitle: 'Agentic AI Slideshow Generator',
        image: 'assets/projects/keyframe.png',
        live: 'https://keyframe-frontend-production.up.railway.app/',
        github: 'https://github.com/KushagraKatiyar06/KeyFrame',
        video: 'https://youtu.be/6y8f5fl7FBA',
        figma: 'https://www.figma.com/design/3hl9m1ituYwaVpuVeSLTGG/KeyFrame',
        users: '~5',
        stack: [
          { label: 'Python',     icon: 'assets/python.svg' },
          { label: 'Next.js',    icon: 'assets/nextjs.svg' },
          { label: 'PostgreSQL', icon: 'assets/postgres.svg' },
          { label: 'AWS',        icon: 'assets/aws.svg' },
          { label: 'Cloudflare', icon: 'assets/cloudflare.svg' },
          { label: 'OpenAI',     icon: 'assets/openai.svg' },
          { label: 'FFmpeg',     icon: 'assets/ffmpeg.svg' },
          { label: 'Figma',      icon: 'assets/figma.svg' },
        ],
      },
      {
        name: 'Alex Willow Platform',
        subtitle: 'Swamp Records',
        image: 'assets/projects/alexwillowcover.png',
        live: 'http://alexwillowmusic.com',
        figma: 'https://www.figma.com/design/AJj1ttznW3Z7to4AeR6cmU/Alex-Willow?node-id=0-1&t=juGwiZwyrqI5RuM9-1',
        stack: [
          { label: 'React',      icon: 'assets/react.svg' },
          { label: 'TypeScript', icon: 'assets/typescript.svg' },
          { label: 'Figma',      icon: 'assets/figma.svg' },
        ],
      },
      {
        name: 'Not My First Swamp',
        subtitle: 'AI Powered UF Routine Builder',
        badge: 'Designathon Winner',
        image: 'assets/projects/notmyfirstswampcover.png',
        live: 'https://notmyfirstswamp.framer.website/',
        video: 'https://www.youtube.com/watch?v=65fP_CaYL_U',
        stack: [
          { label: 'Framer',     icon: 'assets/framer.svg' },
          { label: 'ShadCN',     icon: 'assets/shadcn.svg' },
          { label: 'TypeScript', icon: 'assets/typescript.svg' },
          { label: 'Gemini',     icon: 'assets/gemini.svg' },
        ],
      },
      {
        name: 'Steam Search',
        subtitle: 'Game Recommendation Engine',
        image: 'assets/projects/steamsearch.png',
        live: 'https://steamsearch-production-622f.up.railway.app/',
        github: 'https://github.com/KushagraKatiyar06/SteamSearch',
        figma: 'https://www.figma.com/design/Gm8e6fNthEUQoPD2yOUdr1/Steam-Search',
        users: '~5',
        stack: [
          { label: 'C++',   icon: 'assets/cpp.svg' },
          { label: 'Crow',  icon: 'assets/crow.svg' },
          { label: 'React', icon: 'assets/react.svg' },
          { label: 'AWS',   icon: 'assets/aws.svg' },
          { label: 'Figma', icon: 'assets/figma.svg' },
        ],
      },
      {
        name: 'Technical Portfolio',
        subtitle: 'Blender Environment + Technical Portfolio',
        image: 'assets/projects/portfoliocover.png',
        live: 'https://kushagrakatiyar06.github.io/Portfolio-v2',
        github: 'https://github.com/KushagraKatiyar06/Portfolio-v2',
        figma: 'https://www.figma.com/design/QWqqPnfRkXt3neiDXrauF1/Portfolio?t=juGwiZwyrqI5RuM9-1',
        stack: [
          { label: 'React',      icon: 'assets/react.svg' },
          { label: 'Blender',    icon: 'assets/blender.svg' },
          { label: 'TypeScript', icon: 'assets/typescript.svg' },
          { label: 'Figma',      icon: 'assets/figma.svg' },
        ],
      },
      {
        name: 'Portfolio (Old)',
        subtitle: 'Portfolio',
        image: 'assets/projects/oldportfoliocover.png',
        live: 'https://kushagrakatiyar06.github.io/Portfolio-v1/',
        github: 'https://github.com/KushagraKatiyar06/Portfolio-v1',
        figma: 'https://www.figma.com/design/QWqqPnfRkXt3neiDXrauF1/Portfolio?t=juGwiZwyrqI5RuM9-1',
        stack: [
          { label: 'Figma',      icon: 'assets/figma.svg' },
          { label: 'HTML',       icon: 'assets/html.svg' },
          { label: 'CSS',        icon: 'assets/css.svg' },
          { label: 'JavaScript', icon: 'assets/javascript.svg' },
        ],
      },
    ],
    technical: [
      {
        name: 'Riva',
        subtitle: 'Agentic AI Browser & GTM Tool',
        image: 'assets/projects/riva.png',
        live: 'https://riva-frontend.pages.dev/',
        github: 'https://github.com/KushagraKatiyar06/Riva',
        video: 'https://youtu.be/WZFLMwTHqyA',
        figma: 'https://www.figma.com/design/k1YBhnEym2hMqIpKttI21B/Riva',
        users: '~5',
        stack: [
          { label: 'Next.js 15', icon: 'assets/nextjs.svg' },
          { label: 'React 19',   icon: 'assets/react.svg' },
          { label: 'TypeScript', icon: 'assets/typescript.svg' },
          { label: 'Python',     icon: 'assets/python.svg' },
          { label: 'Cloudflare', icon: 'assets/cloudflare.svg' },
          { label: 'Gemini',     icon: 'assets/gemini.svg' },
          { label: 'Figma',      icon: 'assets/figma.svg' },
        ],
      },
      {
        name: 'KeyFrame',
        subtitle: 'Agentic AI Slideshow Generator',
        image: 'assets/projects/keyframe.png',
        live: 'https://keyframe-frontend-production.up.railway.app/',
        github: 'https://github.com/KushagraKatiyar06/KeyFrame',
        video: 'https://youtu.be/6y8f5fl7FBA',
        figma: 'https://www.figma.com/design/3hl9m1ituYwaVpuVeSLTGG/KeyFrame',
        users: '~5',
        stack: [
          { label: 'Python',     icon: 'assets/python.svg' },
          { label: 'Next.js',    icon: 'assets/nextjs.svg' },
          { label: 'PostgreSQL', icon: 'assets/postgres.svg' },
          { label: 'AWS',        icon: 'assets/aws.svg' },
          { label: 'Cloudflare', icon: 'assets/cloudflare.svg' },
          { label: 'OpenAI',     icon: 'assets/openai.svg' },
          { label: 'FFmpeg',     icon: 'assets/ffmpeg.svg' },
          { label: 'Figma',      icon: 'assets/figma.svg' },
        ],
      },
      {
        name: 'UseProtechtion',
        subtitle: 'Agentic AI Malware Tracking System',
        badge: 'Hackathon Winner',
        image: 'assets/projects/useprotechtion.png',
        github: 'https://github.com/KushagraKatiyar06/useprotech.tion',
        video: 'https://www.youtube.com/watch?v=DujEn2ixbS0&t=6s',
        stack: [
          { label: 'Python',  icon: 'assets/python.svg' },
          { label: 'Next.js', icon: 'assets/nextjs.svg' },
          { label: 'Docker',  icon: 'assets/docker.svg' },
        ],
      },
      {
        name: 'Buddy, Lock In!',
        subtitle: '3D Multiplayer Computer Vision Game',
        badge: 'Hackathon Winner',
        image: 'assets/projects/buddylockin.png',
        video: 'https://www.youtube.com/watch?v=SI3UrrGbyZo',
        github: 'https://github.com/NSang22/buddylockin',
        stack: [
          { label: 'React',     icon: 'assets/react.svg' },
          { label: 'Node.js',   icon: 'assets/nodejs.svg' },
          { label: 'Vite',      icon: 'assets/vite.svg' },
          { label: 'Blender',   icon: 'assets/blender.svg' },
          { label: 'Socket.io', icon: 'assets/socket.svg' },
          { label: 'MediaPipe', icon: 'assets/mediapipe.svg' },
          { label: 'Gemini',    icon: 'assets/gemini.svg' },
        ],
      },
      {
        name: 'Steam Search',
        subtitle: 'Game Recommendation Engine',
        image: 'assets/projects/steamsearch.png',
        live: 'https://steamsearch-production-622f.up.railway.app/',
        github: 'https://github.com/KushagraKatiyar06/SteamSearch',
        figma: 'https://www.figma.com/design/Gm8e6fNthEUQoPD2yOUdr1/Steam-Search',
        users: '~5',
        stack: [
          { label: 'C++',   icon: 'assets/cpp.svg' },
          { label: 'Crow',  icon: 'assets/crow.svg' },
          { label: 'React', icon: 'assets/react.svg' },
          { label: 'AWS',   icon: 'assets/aws.svg' },
          { label: 'Figma', icon: 'assets/figma.svg' },
        ],
      },
      {
        name: 'Train of Four \u2014 Computer Vision',
        subtitle: 'Dream Team Engineering',
        image: 'assets/projects/trainoffourcover.png',
        figma: 'https://www.figma.com/design/9xN80lyUwTB49QHRoiEFOM/Train-of-Four?node-id=0-1&t=xCj48S77fSBcetZM-1',
        stack: [
          { label: 'Python',    icon: 'assets/python.svg' },
          { label: 'Java',      icon: 'assets/java.svg' },
          { label: 'Kotlin',    icon: 'assets/kotlin.svg' },
          { label: 'MediaPipe', icon: 'assets/mediapipe.svg' },
          { label: 'Figma',     icon: 'assets/figma.svg' },
        ],
      },
      {
        name: 'Technical Portfolio',
        subtitle: 'Blender Environment + Technical Portfolio',
        image: 'assets/projects/portfoliocover.png',
        live: 'https://kushagrakatiyar06.github.io/Portfolio-v2',
        github: 'https://github.com/KushagraKatiyar06/Portfolio-v2',
        figma: 'https://www.figma.com/design/QWqqPnfRkXt3neiDXrauF1/Portfolio?t=juGwiZwyrqI5RuM9-1',
        stack: [
          { label: 'React',      icon: 'assets/react.svg' },
          { label: 'Blender',    icon: 'assets/blender.svg' },
          { label: 'TypeScript', icon: 'assets/typescript.svg' },
          { label: 'Figma',      icon: 'assets/figma.svg' },
        ],
      },
    ],
    design: [
      {
        name: 'Alex Willow Platform',
        subtitle: 'Swamp Records',
        image: 'assets/projects/alexwillowcover.png',
        live: 'http://alexwillowmusic.com',
        figma: 'https://www.figma.com/design/AJj1ttznW3Z7to4AeR6cmU/Alex-Willow?node-id=0-1&t=juGwiZwyrqI5RuM9-1',
        stack: [
          { label: 'React',      icon: 'assets/react.svg' },
          { label: 'TypeScript', icon: 'assets/typescript.svg' },
          { label: 'Figma',      icon: 'assets/figma.svg' },
        ],
      },
      {
        name: 'Drift Zero',
        subtitle: 'Optimal Satellite Path + Adversary Analysis',
        badge: 'Hackathon Winner',
        image: 'assets/projects/driftzerocover.png',
        github: 'https://github.com/eshadesigns/Drift-Zero',
        video: 'https://youtu.be/QrSg8taswJk',
        stack: [
          { label: 'React',      icon: 'assets/react.svg' },
          { label: 'TypeScript', icon: 'assets/typescript.svg' },
        ],
      },
      {
        name: 'Not My First Swamp',
        subtitle: 'AI Powered UF Routine Builder',
        badge: 'Designathon Winner',
        image: 'assets/projects/notmyfirstswampcover.png',
        live: 'https://notmyfirstswamp.framer.website/',
        video: 'https://www.youtube.com/watch?v=65fP_CaYL_U',
        stack: [
          { label: 'Framer',     icon: 'assets/framer.svg' },
          { label: 'ShadCN',     icon: 'assets/shadcn.svg' },
          { label: 'TypeScript', icon: 'assets/typescript.svg' },
          { label: 'Gemini',     icon: 'assets/gemini.svg' },
        ],
      },
      {
        name: 'CFSG UF Research Lab Redesign',
        subtitle: 'Gator User Design',
        image: 'assets/projects/cfsg.png',
        figma: 'https://www.figma.com/design/VDXqeQGoIH2rbVGeHfXZj0/Computing-For-Social-Good',
        stack: [
          { label: 'Figma', icon: 'assets/figma.svg' },
          { label: 'Canva', icon: 'assets/canva.svg' },
        ],
      },
      {
        name: 'Student Club Management Portal',
        subtitle: 'Computing Student Union',
        image: 'assets/projects/csucover.png',
        figma: 'https://www.figma.com/design/oHhMlu5Mf3uzGOKRc3q7YL/Computing-Student-Union',
        stack: [
          { label: 'Figma',  icon: 'assets/figma.svg' },
          { label: 'ShadCN', icon: 'assets/shadcn.svg' },
        ],
      },
      {
        name: 'RTS Ride Redesign',
        subtitle: 'Public Bus Tracking App',
        image: 'assets/projects/rtsredesign.png',
        figma: 'https://www.figma.com/design/L88Lrfqj2GbR6ms9eAUEzm/Gainesville-RTS-Ride-Redesign',
        video: 'https://youtu.be/oSKMU-Bmg8U',
        stack: [
          { label: 'Figma',  icon: 'assets/figma.svg' },
          { label: 'ShadCN', icon: 'assets/shadcn.svg' },
          { label: 'Canva',  icon: 'assets/canva.svg' },
        ],
      },
      {
        name: 'Portfolio (Old)',
        subtitle: 'Portfolio',
        image: 'assets/projects/oldportfoliocover.png',
        live: 'https://kushagrakatiyar06.github.io/Portfolio-v1/',
        github: 'https://github.com/KushagraKatiyar06/Portfolio-v1',
        figma: 'https://www.figma.com/design/QWqqPnfRkXt3neiDXrauF1/Portfolio?t=juGwiZwyrqI5RuM9-1',
        stack: [
          { label: 'Figma',      icon: 'assets/figma.svg' },
          { label: 'HTML',       icon: 'assets/html.svg' },
          { label: 'CSS',        icon: 'assets/css.svg' },
          { label: 'JavaScript', icon: 'assets/javascript.svg' },
        ],
      },
      {
        name: 'Florida Fun',
        subtitle: 'Amusement Park Mobile & Web Screens',
        badge: 'BPA National Finalists',
        image: 'assets/projects/floridafun.png',
        drive: 'https://drive.google.com/drive/folders/1r7JxSu1JuPqJ2nzgcKDRB8hQrKfjRZBe?usp=drive_link',
        stack: [
          { label: 'AdobeXD', icon: 'assets/adobexd.svg' },
          { label: 'Canva',   icon: 'assets/canva.svg' },
        ],
      },
    ],
  },
}
